version: "3"

x-shared: &shared
  build:
    context: .
    dockerfile: Dockerfile
  restart: always
  image: yy2473/mail_my_sms:arm-latest
  environment:
    SENDGRID_API_KEY: ${SENDGRID_API_KEY}
  devices:
    - /dev/ttyUSB0:/dev/mobile

services:
  worker:
    <<: *shared
    container_name: mail_my_sms_worker
    command: "python ./mail_me_my_sms/main.py"

  server:
    <<: *shared
    container_name: mail_my_sms_server
    ports:
      - "4000:4000"
    command: "python ./mail_me_my_sms/server.py"
